"""empty message

Revision ID: 52372d58e284
Revises: 8871d6180af4
Create Date: 2021-03-17 01:53:05.639533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52372d58e284'
down_revision = '8871d6180af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.String(length=65), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###
